In [1]:
import numpy as np

In [2]:
#array slicing
arr = np.arange(20, 31)

In [3]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
arr[3]

23

In [5]:
arr[0]

20

In [6]:
arr[1:5]

array([21, 22, 23, 24])

In [7]:
arr[:6]

array([20, 21, 22, 23, 24, 25])

In [8]:
arr[5:]

array([25, 26, 27, 28, 29, 30])

In [10]:
#broadcasting
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,  25,  26,  27,  28,  29,  30])

In [12]:
second_arr = np.arange(20, 30)

In [13]:
second_arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
second_arr[:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
#to make copy of array
second_arr_copy = np.copy(arr)

In [17]:
second_arr_copy

array([100, 100, 100, 100, 100,  25,  26,  27,  28,  29,  30])

In [18]:
#slicing of 2D array

In [20]:
arr_2d = np.array([[3,4,5],[6,7,8],[9,10,11]])

In [21]:
arr_2d

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
#slicing of matrix has two methods

In [23]:
arr_2d[0][1]

4

In [24]:
arr_2d[1]

array([6, 7, 8])

In [25]:
arr_2d[1,1]

7

In [26]:
arr_2d[:2,1:]

array([[4, 5],
       [7, 8]])

In [27]:
arr_2d[:2]

array([[3, 4, 5],
       [6, 7, 8]])

In [28]:
arr = np.arange(0,11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#conditional array

In [31]:
cond_arr = arr>5

In [32]:
cond_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [35]:
arr[cond_arr]

array([ 6,  7,  8,  9, 10])

In [36]:
arr[arr<3]

array([0, 1, 2])

In [37]:
 arr_2d = np.arange(50).reshape(5,10)

In [38]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
arr_2d[2:4,4:]

array([[24, 25, 26, 27, 28, 29],
       [34, 35, 36, 37, 38, 39]])