In [1]:
import numpy as np

In [2]:
a = 5

In [3]:
b = [1,2,3]

In [4]:
c = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
vector = np.array(b)

In [6]:
vector

array([1, 2, 3])

In [7]:
matrix = np.array(c)

In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
x = np.arange(0, 11)

In [13]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.49452795, 0.41479783, 0.04306522, 0.62513696, 0.67295575])

In [20]:
np.random.randn(2)

array([-1.19751168,  0.01780071])

In [21]:
np.random.randint(10,100)

81

In [22]:
np.random.randint(10,100,20)

array([29, 55, 85, 56, 72, 43, 20, 31, 90, 73, 79, 90, 96, 63, 96, 83, 24,
       28, 31, 55])

In [23]:
random_arr = np.random.randint(0,50,10)

In [24]:
random_arr

array([21, 22, 39, 46, 43, 39, 35, 46, 25, 34])

In [27]:
random_arr.reshape(5,2)

array([[21, 22],
       [39, 46],
       [43, 39],
       [35, 46],
       [25, 34]])

In [28]:
from numpy.random import randint

In [36]:
arr

NameError: name 'arr' is not defined